### ISSUE TITLE
/routes/api.js:268 Unexpected Token

### ISSUE THREAD

**Issue by nzurku** [nayrnet/raspipc#4]
```
pi@raspberrypi:~/raspipc $ node app.js
/home/pi/raspipc/routes/api.js:268
  omxProc[camera].on('close', (code, signal)) => {
                                              ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/pi/raspipc/app.js:12:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

Seems that there is an issue here unless I'm missing something. Can you take a look at this?

**Comment by nzurku** [comment]
Had to update node, my mistake.

`sudo npm cache clean -f

sudo npm install -g n

sudo n stable`

**Comment by nayrnet** [comment]
this is not in a working state currently, I have hit a few issues with dbus and have not checked in a fix yet..
